
#sendEmail config
spring:
  mail:
    host: xxxx  #邮箱服务器地址
    port: 25
    username: xxxx　 #用户名
    password: xxxx　 #密码
    default-encoding: UTF-8

#自定义 以谁来发送邮件
mail:
  fromMail:
    addr: xxx@xx.com

