

spring:
  application:
    name: spring-boot-rabbitmq

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  redis:
    host: localhost
    port: 6379

server:
  port: 8080
