
server:
  port: 8080

#https://blog.csdn.net/sy793314598/article/details/80719224
spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 60s
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
